### ISSUE TITLE
infiniBand SRI-OV CNI failed to configure VF "VF ib2 GUID is not valid"

### ISSUE THREAD

**Issue by seb-835** [k8snetworkplumbingwg/sriov-network-operator#307]
Hi Team,

i think i am really near to get it work, 
but got this in describing my testing pod: 

```
 Normal   AddedInterface          2s    multus             Add eth0 [10.233.117.195/32] from cni0
  Warning  FailedCreatePodSandBox  1s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "88aee8b5e04d60a0fdfe9437888521e2f49a170b67ce574adf571f05f644bf74": [default/test-sriov-ib-pod:example-sriov-ib-network]: error adding container to network "example-sriov-ib-network": infiniBand SRI-OV CNI failed to configure VF "VF ib2 GUID is not valid"
```

i use the following manifest to test :

```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: infiniband-sriov
  namespace: cattle-sriov-system 
spec:
  deviceType: netdevice
  mtu: 1500
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  nicSelector:
    vendor: "15b3"
    deviceID: "101c"
  linkType: ib
  isRdma: true
  numVfs: 4 
  priority: 90
  resourceName: mlnxnics
```
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovIBNetwork
metadata:
  name: example-sriov-ib-network
  namespace: cattle-sriov-system
spec:
  ipam: |
    {
     "type": "whereabouts",
     "range": "192.168.5.225/28"
    }
  resourceName: mlnxnics
  linkState: enable
  networkNamespace: default
```
```
kind: Pod
metadata:
  name: test-sriov-ib-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: example-sriov-ib-network
spec:
  containers:
    - name: test-sriov-ib-pod
      image: centos/tools
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - sleep inf
      securityContext:
        capabilities:
          add: [ "IPC_LOCK" ]
      resources:
        requests:
         rancher.io/mlnxnics: "1"
        limits:
          rancher.io/mlnxnics: "1
```

can you give me advice to fix it ?
Thanks a lot
