### ISSUE TITLE
Add Intel E310 Network Adapter PF id: 1521 as supported device for SR-IOV #329

### ISSUE THREAD

**Issue by tlehman** [k8snetworkplumbingwg/sriov-network-operator#342]
**Model**: Intel Corporation I350 Gigabit Network Connection
**Vendor**: 8086
**Device**: 1521

Platform testing was done on Harvester HCI 1.0.2

```sh
kubectl get node titan -o yaml | yq .status.allocatable                                       
```

```
cpu: "4"
devices.kubevirt.io/kvm: 1k
devices.kubevirt.io/sev: "0"
devices.kubevirt.io/tun: 1k
devices.kubevirt.io/vhost-net: 1k
ephemeral-storage: "99894567244"
hugepages-1Gi: "0"
hugepages-2Mi: "0"
memory: 32724368Ki
pods: "110"
```

```sh
kubectl -n sriov-network-operator get sriovnetworknodestates.sriovnetwork.openshift.io titan -o yaml | yq .status.interfaces
```

```
- deviceID: "1521"
  driver: igb
  linkType: ETH
  mac: 5c:ba:2c:20:37:68
  mtu: 1500
  name: eno1
  pciAddress: "0000:02:00.0"
  totalvfs: 7
  vendor: "8086"
- deviceID: "1521"
  driver: igb
  linkType: ETH
  mac: 5c:ba:2c:20:37:69
  mtu: 1500
  name: eno2
  pciAddress: "0000:02:00.1"
  totalvfs: 7
  vendor: "8086"
- deviceID: "1521"
  driver: igb
  linkType: ETH
  mac: 5c:ba:2c:20:37:6a
  mtu: 1500
  name: eno3
  pciAddress: "0000:02:00.2"
  totalvfs: 7
  vendor: "8086"
- Vfs:
    - deviceID: "1520"
      driver: igbvf
      mac: 4e:69:4f:9c:3a:80
      mtu: 1500
      name: enp2s16f3
      pciAddress: "0000:02:10.3"
      vendor: "8086"
      vfID: 0
    - deviceID: "1520"
      driver: igbvf
      mac: 82:07:c6:80:63:1f
      mtu: 1500
      name: enp2s16f7
      pciAddress: "0000:02:10.7"
      vendor: "8086"
      vfID: 1
    - deviceID: "1520"
      driver: igbvf
      mac: da:47:4a:68:63:60
      mtu: 1500
      name: enp2s17f3
      pciAddress: "0000:02:11.3"
      vendor: "8086"
      vfID: 2
    - deviceID: "1520"
      driver: igbvf
      mac: d6:4a:c1:e4:65:1d
      mtu: 1500
      name: enp2s17f7
      pciAddress: "0000:02:11.7"
      vendor: "8086"
      vfID: 3
  deviceID: "1521"
  driver: igb
  linkSpeed: 1000 Mb/s
  linkType: ETH
  mac: 5c:ba:2c:20:37:6b
  mtu: 1500
  name: eno4
  numVfs: 4
  pciAddress: "0000:02:00.3"
  totalvfs: 7
  vendor: "8086"
```
