### ISSUE TITLE
[Helm Chart] Remove default node affinity in sriov-network-operator deployment and sriov-config-daemon

### ISSUE THREAD

**Issue by tariq1890** [k8snetworkplumbingwg/sriov-network-operator#442]
Setting a [default node anti-affinity](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/1c6e1b3b1f6d70882d6245e5ccff4e9b70bf3948/deployment/sriov-network-operator/values.yaml#L11) is too opinionated and it makes it especially tricky for people who are on Managed Kubernetes Clusters without visible control planes or clusters who just don't use the node labeling conventions assumed by the helm chart.

Moreover, overriding the default node AntiAffinity is not possible. Since we use sriov-network-operator as a helm subchart, we are also unable to unset this default node antiAffinity value. Although helm provides a way to unset default values by setting `null` as the value in the value override file, this does not work for sub-charts.

The best default is not to set any antiAffinity and leave it completely to the users. I believe this is the pattern followed by most OSS K8s operators

**Comment by adrianchiris** [comment]
i dont see node anti-affinity in our helm chart. do you mean node affinity ?

overriding it with something like:

``
sriov-network-operator:
  affinity:
    nodeAffinity: {}
``

wont work ?

**Comment by tariq1890** [comment]
Sorry, I meant node affinity. Yes, that doesn't work because of the way helm performs map merges when processing override values files

**Comment by tariq1890** [comment]
I tried this again btw. 

When I use these values, the override happens as expected:
```
sriov-network-operator:
  operator:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "kubernetes.io/os"
                  operator: In
                  values: [ "linux" ]
```

But when I use this, the default values get used instead:

```
sriov-network-operator:
  operator:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "kubernetes.io/os"
                  operator: In
                  values: [ "linux" ]
```
