### ISSUE TITLE
There should be nothing that uses a node selector/affinity that is not easily configurable at deploy time

### ISSUE THREAD

**Issue by ns-rlewkowicz** [k8snetworkplumbingwg/sriov-network-operator#507]
This is an interesting project. I wonder what the reasoning was behind the need for an aggressive reconciliation loop over a slew of well established deployment models and tools. 

It worked great in a dev env, trying to incorporate this into an existing environment has been a nightmare. 

This fixes config daemon: 
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  annotations:
  name: default
  namespace: sriov-network-operator
spec:
  configDaemonNodeSelector:
    node-role.kubernetes.io/worker": "true"
  enableInjector: true
  enableOperatorWebhook: true
  logLevel: 2
 ```
 
But even this is awkward. It doesn't seem to cycle the pods automatically after application. 

Then the other DS won't launch. There's a bunch of hard coded node labels.
