### ISSUE TITLE
Not documented how to deploy the injector

### ISSUE THREAD

**Issue by manuelbuil** [k8snetworkplumbingwg/sriov-network-operator#70]
I'd like to deploy the operator with the injector, however, I can't find how to do that.

When I deploy the operator, a default SriovOperatorConfig is created with:
```
  spec:
    enableInjector: false
    enableOperatorWebhook: false
    logLevel: 2
```
By changing that to true, I don't see any result. It'd be nice to document this functionality
