### ISSUE TITLE
Intel XXV710 - Devlink query for eswitch mode is not supported for device

### ISSUE THREAD

**Issue by ns-rlewkowicz** [k8snetworkplumbingwg/sriov-network-operator#716]
I have a `Intel Corporation Ethernet Controller XXV710 for 25GbE SFP28`. 

I can successfully create 30 VFs in sriov mode. 

```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vfio1
  namespace: sriov-network-operator
spec:
  deviceType: vfio-pci
  eSwitchMode: legacy
  needVhostNet: true
  nicSelector:
    pfNames:
    - enp1s0f0#0-30
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  numVfs: 30
  priority: 90
  resourceName: net1-dpdk
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vfio2
  namespace: sriov-network-operator
spec:
  deviceType: vfio-pci
  eSwitchMode: legacy
  needVhostNet: true
  nicSelector:
    pfNames:
    - enp1s0f1#0-30
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  numVfs: 30
  priority: 90
  resourceName: net2-dpdk
```

I would like to create an additional 30 in netdevice mode as outlined here: https://docs.openshift.com/container-platform/4.15/networking/hardware_networks/configuring-sriov-device.html#nw-sriov-nic-partitioning_configuring-sriov-device
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: netdevice2
  namespace: sriov-network-operator
spec:
  deviceType: netdevice
  needVhostNet: true
  nicSelector:
    pfNames:
    - enp1s0f1#31-61
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  numVfs: 30
  priority: 91
  resourceName: net1-host
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: netdevice1
  namespace: sriov-network-operator
spec:
  needVhostNet: true
  deviceType: netdevice
  nicSelector:
    pfNames:
    - enp1s0f0#31-61
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  numVfs: 30
  priority: 91
  resourceName: net2-host
```

However, the plugin spams:
```
I0617 15:00:09.533327       1 utils.go:82] Devlink query for eswitch mode is not supported for device 0000:01:05.2. error getting devlink device attributes for net device 0000:01:00.0 no such device
```

Now I'm reading that perhaps the 700 series does not support "Flow Bifurcation"? So you might not be able to do that with this card?
